/* Allegro datafile object indexes, produced by dat v4.2.3 (SVN), MinGW32 */
/* Datafile: defnot.dat */
/* Date: Sun Sep 16 23:47:31 2007 */
/* Do not hand edit! */

#define ANGELS_PCX                       0        /* BMP  */
#define BG2_PCX                          1        /* BMP  */
#define BG3_PCX                          2        /* BMP  */
#define BG_PCX                           3        /* BMP  */
#define DEVIL_PCX                        4        /* BMP  */
#define DEVIL_WALKING00_PCX              5        /* BMP  */
#define DEVIL_WALKING01_PCX              6        /* BMP  */
#define DEVIL_WALKING02_PCX              7        /* BMP  */
#define DEVIL_WALKING03_PCX              8        /* BMP  */
#define DEVIL_WALKING04_PCX              9        /* BMP  */
#define DEVIL_WALKING05_PCX              10       /* BMP  */
#define DEVIL_WALKING06_PCX              11       /* BMP  */
#define DEVIL_WALKING07_PCX              12       /* BMP  */
#define DISQUAL_PCX                      13       /* BMP  */
#define FONT_PCX                         14       /* FONT */
#define PALETTE_PCX                      15       /* PAL  */
#define PEOPLE_PCX                       16       /* BMP  */
#define TAIL00_PCX                       17       /* BMP  */
#define TAIL01_PCX                       18       /* BMP  */
#define TAIL02_PCX                       19       /* BMP  */
#define TAIL03_PCX                       20       /* BMP  */
#define TAIL04_PCX                       21       /* BMP  */
#define TAIL05_PCX                       22       /* BMP  */
#define TAIL06_PCX                       23       /* BMP  */
#define TAIL07_PCX                       24       /* BMP  */
#define TAIL08_PCX                       25       /* BMP  */
#define TAIL09_PCX                       26       /* BMP  */
#define TAIL10_PCX                       27       /* BMP  */
#define TAIL11_PCX                       28       /* BMP  */
#define TAIL12_PCX                       29       /* BMP  */
#define TAIL13_PCX                       30       /* BMP  */
#define TAIL14_PCX                       31       /* BMP  */
#define TAIL15_PCX                       32       /* BMP  */
#define TAIL16_PCX                       33       /* BMP  */
#define TAIL17_PCX                       34       /* BMP  */
#define TAIL18_PCX                       35       /* BMP  */
#define TAIL19_PCX                       36       /* BMP  */
#define TAIL20_PCX                       37       /* BMP  */
#define TAIL21_PCX                       38       /* BMP  */
#define TAIL22_PCX                       39       /* BMP  */
#define TAIL23_PCX                       40       /* BMP  */
#define TAIL24_PCX                       41       /* BMP  */
#define TAIL25_PCX                       42       /* BMP  */
#define TILES_PCX                        43       /* BMP  */
#define WINGS00_PCX                      44       /* BMP  */
#define WINGS01_PCX                      45       /* BMP  */
#define WINGS02_PCX                      46       /* BMP  */
#define WINGS03_PCX                      47       /* BMP  */
#define WINGS04_PCX                      48       /* BMP  */
#define WINGS05_PCX                      49       /* BMP  */
#define WINGS06_PCX                      50       /* BMP  */
#define WINGS07_PCX                      51       /* BMP  */
#define WINGS08_PCX                      52       /* BMP  */
#define WINGS09_PCX                      53       /* BMP  */
#define WINGS10_PCX                      54       /* BMP  */
#define WINGS11_PCX                      55       /* BMP  */

